name: TravelAgent
summary: This is a travel agent deployed into a foundry project with associated azure resources.
description: Deploys a travel agent.
templatePath: travelagent.bicep
parameters:
- id: "location"
  name: "Location"
  description: "The location of the resource group for your project"
  type: "string"
  required: false
- id: "account_name"
  name: "Bing Account Name"
  description: "Unique name for the Bing grounding resource"
  type: "string"
  required: false
runner: Bicep
