name: TravelAgent
summary: This is a travel agent deployed into a foundry project with associated azure resources.
description: Deploys a travel agent.
templatePath: travelagent.bicep
parameters:
- id: "PROJECT_ENDPOINT"
  name: "Project Endpoint"
  description: "The endpoint for your project (e.g., https://<your-ai-services-account-name>.services.ai.azure.com/api/projects/<your-project-name>)"
  type: "string"
  required: false
- id: "MODEL_DEPLOYMENT_NAME"
  name: "Model Deployment Name"
  description: "The name of your model deployment."
  type: "string"
  required: false
- id: "bingAccountName"
  name: "Bing Account Name"
  description: "Unique name for the Bing grounding resource"
  type: "string"
  required: false
- id: "bingSku"
  name: "Bing SKU"
  description: "Pricing tier (e.g., S1)"
  type: "string"
  required: false
- id: "connectionName"
  name: "Connection Name"
  description: "Name for the AML connection to Bing"
  type: "string"
  required: false
- id: "amlWorkspaceResourceName"
  name: "AML Workspace Resource Name"
  description: "Name of the AI Project or the AML workspace"
  type: "string"
  required: false
- id: "bingTargetEndpoint"
  name: "Bing Target Endpoint"
  description: "Bing API endpoint (defaults to https://api.bing.microsoft.com/)"
  type: "string"
  required: false
  default: "https://api.bing.microsoft.com/"
runner: Bicep
